const SUPABASE_URL='https://yrhjklnxjchfxbcpopfd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable__SxBsu9fKpxjS7YPaAyTqA_lqwZW62K';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let user=null,profile=null,locations=[],equipment=[];
const extLabel={dry_chemical:'เคมีแห้ง',co2:'CO2',fire_ade:'Fire Ade',avd:'AVD',bf2000:'BF2000'};
const kindLabel={cabinet:'ตู้ดับเพลิง',extinguisher:'ถังดับเพลิง'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(id,text,ok=false){const e=$(id);e.textContent=text;e.style.color=ok?'#166534':'#b91c1c';setTimeout(()=>e.textContent='',3500)}
$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.tab+'Tab').classList.remove('hidden')});
function resetLoc(){$('#locationForm').reset();$('#locId').value=''}
function resetEq(){$('#equipmentForm').reset();$('#eqId').value='';$('#eqType').value='cabinet';$('#eqExt').value='';$('#eqType').onchange()}
$('#locReset').onclick=resetLoc;$('#eqReset').onclick=resetEq;
async function boot(){const s=await db.auth.getSession();user=s.data.session?.user||null;if(!user){$('#access').textContent='กรุณาเข้าสู่ระบบก่อนใช้งานหน้านี้';return}const p=await db.from('profiles').select('full_name,role,is_active').eq('id',user.id).single();if(p.error||!p.data||p.data.role!=='admin'||!p.data.is_active){$('#access').textContent='⛔ หน้านี้สำหรับผู้ดูแลระบบ (admin) เท่านั้น';$('#who').textContent=p.data?.full_name||user.email||'';return}profile=p.data;$('#who').textContent=`${profile.full_name} • admin`;$(' #access'.trim()).classList.add('hidden');$('#panel').classList.remove('hidden');await refreshAll()}
async function refreshAll(){await loadLocations();await loadEquipment();renderLocationSelect();renderLocations();renderEquipment()}
async function loadLocations(){const r=await db.from('locations').select('*').order('location_code');if(r.error){msg('#locMsg','โหลดจุดติดตั้งไม่สำเร็จ: '+r.error.message);return}locations=r.data||[]}
async function loadEquipment(){const r=await db.from('equipment').select('*, locations(location_code,location_name,floor)').order('equipment_code');if(r.error){msg('#eqMsg','โหลดอุปกรณ์ไม่สำเร็จ: '+r.error.message);return}equipment=r.data||[]}
function renderLocationSelect(){const s=$('#eqLocation');s.innerHTML='<option value="">เลือกจุดติดตั้ง</option>'+locations.filter(x=>x.is_active).map(x=>`<option value="${x.id}">${esc(x.location_code||'—')} • ${esc(x.location_name)} • ${esc(x.floor)}</option>`).join('')}
function renderLocations(){const q=$('#locSearch').value.trim().toLowerCase();const list=locations.filter(x=>[x.location_code,x.location_name,x.floor,x.building,x.zone].join(' ').toLowerCase().includes(q));$('#locBody').innerHTML=list.map(x=>`<tr><td>${esc(x.location_code||'—')}</td><td><b>${esc(x.location_name)}</b><br><small>${esc(x.zone||'')}</small></td><td>${esc(x.floor)}</td><td>${esc(x.building||'—')}</td><td><span class="badge ${x.is_active?'':'off'}">${x.is_active?'ใช้งาน':'ปิดใช้งาน'}</span></td><td><button class="btn secondary" data-edit-loc="${x.id}">แก้ไข</button> ${x.is_active?`<button class="btn danger" data-toggle-loc="${x.id}">ปิดใช้งาน</button>`:`<button class="btn primary" data-toggle-loc="${x.id}">เปิดใช้งาน</button>`}</td></tr>`).join('')||'<tr><td colspan="6" class="loading">ไม่พบข้อมูล</td></tr>';$$('[data-edit-loc]').forEach(b=>b.onclick=()=>editLocation(b.dataset.editLoc));$$('[data-toggle-loc]').forEach(b=>b.onclick=()=>toggleLocation(b.dataset.toggleLoc))}
function renderEquipment(){const q=$('#eqSearch').value.trim().toLowerCase(),kind=$('#eqKind').value;const list=equipment.filter(x=>(kind==='all'||x.equipment_type===kind)&&[x.equipment_code,x.equipment_label,x.equipment_type,x.extinguisher_type,x.locations?.location_name,x.locations?.floor].join(' ').toLowerCase().includes(q));$('#eqBody').innerHTML=list.map(x=>`<tr><td><b>${esc(x.equipment_code)}</b><br><small>${esc(x.equipment_label||'')}</small></td><td>${kindLabel[x.equipment_type]}</td><td>${esc(x.locations?.location_name||'—')}<br><small>${esc(x.locations?.floor||'')}</small></td><td>${esc(extLabel[x.extinguisher_type]||'—')}</td><td>${x.size_lbs??'—'} ${x.size_lbs?'lbs':''}</td><td><span class="badge ${x.is_active?'':'off'}">${x.is_active?'ใช้งาน':'ปิดใช้งาน'}</span></td><td><button class="btn secondary" data-edit-eq="${x.id}">แก้ไข</button> ${x.is_active?`<button class="btn danger" data-toggle-eq="${x.id}">ปิดใช้งาน</button>`:`<button class="btn primary" data-toggle-eq="${x.id}">เปิดใช้งาน</button>`}</td></tr>`).join('')||'<tr><td colspan="7" class="loading">ไม่พบข้อมูล</td></tr>';$$('[data-edit-eq]').forEach(b=>b.onclick=()=>editEquipment(b.dataset.editEq));$$('[data-toggle-eq]').forEach(b=>b.onclick=()=>toggleEquipment(b.dataset.toggleEq))}
function editLocation(id){const x=locations.find(v=>v.id===id);if(!x)return;$('#locId').value=x.id;$('#locCode').value=x.location_code||'';$('#locName').value=x.location_name;$('#locFloor').value=x.floor;$('#locBuilding').value=x.building||'';$('#locZone').value=x.zone||'';$('#locDesc').value=x.description||'';scrollTo({top:0,behavior:'smooth'})}
function editEquipment(id){const x=equipment.find(v=>v.id===id);if(!x)return;$$('.tabs button').find(x=>x.dataset.tab==='equipment').click();$('#eqId').value=x.id;$('#eqCode').value=x.equipment_code;$('#eqType').value=x.equipment_type;$('#eqLocation').value=x.location_id;$('#eqExt').value=x.extinguisher_type||'';$('#eqSize').value=x.size_lbs??'';$('#eqBrand').value=x.brand||'';$('#eqModel').value=x.model||'';$('#eqSerial').value=x.serial_number||'';$('#eqInstall').value=x.installation_date||'';$('#eqLabel').value=x.equipment_label||'';$('#eqType').onchange();scrollTo({top:0,behavior:'smooth'})}
async function toggleLocation(id){const x=locations.find(v=>v.id===id);if(!x)return;if(!confirm(`${x.is_active?'ปิดใช้งาน':'เปิดใช้งาน'} จุดติดตั้ง ${x.location_name} ?`))return;const r=await db.from('locations').update({is_active:!x.is_active,updated_at:new Date().toISOString()}).eq('id',id);if(r.error){msg('#locMsg','แก้ไขสถานะไม่สำเร็จ: '+r.error.message);return}await refreshAll()}
async function toggleEquipment(id){const x=equipment.find(v=>v.id===id);if(!x)return;if(!confirm(`${x.is_active?'ปิดใช้งาน':'เปิดใช้งาน'} อุปกรณ์ ${x.equipment_code} ?`))return;const r=await db.from('equipment').update({is_active:!x.is_active,updated_at:new Date().toISOString()}).eq('id',id);if(r.error){msg('#eqMsg','แก้ไขสถานะไม่สำเร็จ: '+r.error.message);return}await refreshAll()}
$('#locationForm').onsubmit=async e=>{e.preventDefault();const id=$('#locId').value;const payload={location_code:$('#locCode').value.trim()||null,location_name:$('#locName').value.trim(),floor:$('#locFloor').value.trim(),building:$('#locBuilding').value.trim()||null,zone:$('#locZone').value.trim()||null,description:$('#locDesc').value.trim()||null,updated_at:new Date().toISOString()};let r=id?await db.from('locations').update(payload).eq('id',id):await db.from('locations').insert(payload);if(r.error){msg('#locMsg','บันทึกไม่สำเร็จ: '+r.error.message);return}msg('#locMsg',id?'แก้ไขจุดติดตั้งแล้ว':'เพิ่มจุดติดตั้งแล้ว',true);resetLoc();await refreshAll()}
$('#equipmentForm').onsubmit=async e=>{e.preventDefault();const id=$('#eqId').value,type=$('#eqType').value,ext=$('#eqExt').value||null;if(type==='extinguisher'&&!ext){msg('#eqMsg','กรุณาเลือกประเภทถัง');return}const payload={equipment_code:$('#eqCode').value.trim(),location_id:$('#eqLocation').value,equipment_type:type,extinguisher_type:type==='extinguisher'?ext:null,size_lbs:$('#eqSize').value?Number($('#eqSize').value):null,brand:$('#eqBrand').value.trim()||null,model:$('#eqModel').value.trim()||null,serial_number:$('#eqSerial').value.trim()||null,installation_date:$('#eqInstall').value||null,equipment_label:$('#eqLabel').value.trim()||null,source_code:$('#eqCode').value.trim(),is_active:true,updated_at:new Date().toISOString()};let r=id?await db.from('equipment').update(payload).eq('id',id):await db.from('equipment').insert(payload);if(r.error){msg('#eqMsg','บันทึกไม่สำเร็จ: '+r.error.message);return}msg('#eqMsg',id?'แก้ไขอุปกรณ์แล้ว':'เพิ่มอุปกรณ์แล้ว',true);resetEq();await refreshAll()}
$('#locSearch').oninput=renderLocations;$('#eqSearch').oninput=renderEquipment;$('#eqKind').onchange=renderEquipment;
$('#eqType').onchange=()=>{const isExt=$('#eqType').value==='extinguisher';$('#eqExt').disabled=!isExt;$('#eqSize').disabled=!isExt;if(!isExt){$('#eqExt').value='';$('#eqSize').value=''}};$('#eqType').onchange();boot();