const KEY='fireSafetyInspectionsV1';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let records=JSON.parse(localStorage.getItem(KEY)||'[]');
const nowText=()=>new Date().toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'});
const dateText=d=>new Date(d).toLocaleDateString('th-TH',{year:'numeric',month:'short',day:'numeric'});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(records));$('#lastSynced').textContent=nowText();renderAll()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function page(p){$$('.page').forEach(x=>x.classList.remove('active-page'));$('#'+p).classList.add('active-page');$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));window.scrollTo({top:0,behavior:'smooth'})}
$$('#nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));$('#newInspection').onclick=()=>page('inspection');$('#addFromList').onclick=()=>page('inspection');
function checkRows(type){
 const rows=type==='cabinet' ? [
  ['สภาพตู้','เช็คสนิม, กระจกแตก, บานพับ'],['สายฉีด','เช็ครอยรั่ว, การพับงอ'],['ชุดแองเกิลวาล์ว','เช็คสภาพวาล์ว, สนิม'],['ยางโอริงหัวจ่าย','เช็คความยืดหยุ่น, การฉีกขาด'],['วาล์วน้ำ','เช็คการเปิด-ปิด, การรั่วซึม']
 ]:[['มาตรวัด','เช็คเข็มอยู่ในแถบสีเขียว'],['ซีล/สลัก','เช็คว่ายังล็อคแน่นหนา ไม่ขาด'],['สายฉีด','เช็คว่าไม่เปื่อย ไม่ตัน'],['สภาพถัง','เช็คสนิม, รอยบุบ, สีถลอก']];
 return rows.map((r,i)=>`<div class="check-row"><div><strong>${r[0]}</strong><small>${r[1]}</small></div><div class="check-status"><label><input required type="radio" name="c${i}" value="good"> ปกติ</label><label><input required type="radio" name="c${i}" value="bad"> ชำรุด</label></div>${(i===rows.length-1||type==='cabinet'&&i===4)?'<input class="check-note" name="note" placeholder="หมายเหตุ / อาการเสีย">':'<span></span>'}</div>`).join('');
}
function renderType(){const type=$('input[name="equipmentType"]:checked').value;$('#cabinetForm').classList.toggle('hidden',type!=='cabinet');$('#extinguisherForm').classList.toggle('hidden',type!=='extinguisher');$('#cabinetForm').innerHTML=type==='cabinet'?`<div class="checklist"><h4>ผลการตรวจตู้ดับเพลิง</h4>${checkRows('cabinet')}</div>`:'';$('#extinguisherForm').innerHTML=type==='extinguisher'?`<div class="fields"><label>ประเภทถัง<select id="extType" required><option>เคมีแห้ง</option><option>CO2</option><option>Fire Ade</option><option>AVD</option></select></label><label>ขนาดปอนด์<input id="extSize" type="number" min="1" required placeholder="เช่น 10, 15, 20"></label></div><div class="checklist"><h4>ผลการตรวจถังดับเพลิง</h4><div id="extChecks">${checkRows('extinguisher')}</div></div>`:''; if(type==='extinguisher') toggleGauge();}
$$('input[name="equipmentType"]').forEach(x=>x.onchange=renderType);
function toggleGauge(){const t=$('#extType');if(!t)return;const row=$$('#extChecks .check-row')[0];row.style.display=t.value==='CO2'?'none':'grid';row.querySelectorAll('input').forEach(x=>x.disabled=t.value==='CO2');}
function setDate(){$('#inspectionDate').value=nowText()}
$('#inspectionForm').addEventListener('reset',()=>setTimeout(()=>{setDate();renderType()},0));
$('#inspectionForm').addEventListener('submit',e=>{e.preventDefault();const type=$('input[name="equipmentType"]:checked').value;const checks=[];const selector=type==='cabinet'?'#cabinetForm .check-row':'#extChecks .check-row';$$(selector).forEach((r,i)=>{if(r.style.display==='none')return;const chosen=r.querySelector('input:checked');checks.push({name:r.querySelector('strong').textContent,status:chosen?.value||'good'})});const bad=checks.filter(x=>x.status==='bad');const r={id:$('#equipmentId').value.trim(),location:$('#location').value.trim(),floor:$('#floor').value,type,extType:type==='extinguisher'?$('#extType').value:'',size:type==='extinguisher'?$('#extSize').value:'',checks,note:e.target.querySelector('[name="note"]')?.value||'',date:new Date().toISOString(),inspector:'นายสมชาย สายตรวจ',status:bad.length?'bad':'good'};if(!r.id||!r.location||!r.floor){toast('กรุณากรอกข้อมูลที่จำเป็นให้ครบ');return}records=records.filter(x=>x.id!==r.id);records.push(r);save();toast('บันทึกข้อมูลเรียบร้อยแล้ว');e.target.reset();setTimeout(()=>page('equipment'),300)});
$('#scanBtn').onclick=()=>toast('ตัวอย่างนี้ใช้ช่องกรอกรหัสแทนเครื่องสแกน QR/Barcode — สามารถเชื่อมกล้องได้ในขั้นถัดไป');
$('#logout').onclick=()=>toast('ออกจากระบบ (Demo)');
function locations(){const a=[...new Set(records.map(r=>r.location))];$('#locationOptions').innerHTML=a.map(x=>`<option value="${esc(x)}">`).join('')}
function renderDashboard(filter=''){const rs=filter?records.filter(r=>r.location.toLowerCase().includes(filter.toLowerCase())):records;const total=rs.length,good=rs.filter(r=>r.status==='good').length,bad=total-good;$('#mTotal').textContent=total;$('#mGood').textContent=good;$('#mBad').textContent=bad;$('#mGoodPct').textContent=total?Math.round(good/total*100)+'%':'0%';$('#mLatest').textContent=records.length?dateText(records[records.length-1].date):'—';$('#legGood').textContent=good;$('#legBad').textContent=bad;const pct=total?good/total:0;$('#donut').style.background=`conic-gradient(#16854d 0 ${pct*360}deg,#dc3342 ${pct*360}deg 360deg)`;$('#donutPct').textContent=Math.round(pct*100)+'%';
 const floors=[...new Set(records.map(r=>r.floor))];const max=Math.max(1,...floors.map(f=>rs.filter(r=>r.floor===f&&r.status==='bad').length));$('#floorChart').innerHTML=(floors.length?floors:['ชั้น 1','ชั้น 2','ชั้น 3']).map(f=>{const n=rs.filter(r=>r.floor===f&&r.status==='bad').length;return `<div class="bar-item"><b>${n}</b><div class="bar" style="height:${Math.max(3,n/max*145)}px"></div><small>${esc(f)}</small></div>`}).join('');
 const types=['เคมีแห้ง','CO2','Fire Ade','AVD'];const counts=types.map(t=>rs.filter(r=>r.extType===t).length);const sum=counts.reduce((a,b)=>a+b,0);let acc=0;const stops=counts.map((n,i)=>{const s=acc/sum*360;acc+=n;return `${['#d93b45','#58677a','#d58a2c','#3b8f65'][i]} ${s}deg ${acc/sum*360}deg`}).join(',');$('#pie').style.background=sum?`conic-gradient(${stops})`:'#e8edf3';$('#typeLegend').innerHTML=types.map((t,i)=>`<span><i class="dot" style="background:${['#d93b45','#58677a','#d58a2c','#3b8f65'][i]}"></i>${t} <b>${counts[i]}</b></span>`).join('');
 const badRs=rs.filter(r=>r.status==='bad').sort((a,b)=>b.date.localeCompare(a.date));$('#alertsBody').innerHTML=badRs.length?badRs.map(r=>`<tr><td><button class="id-link" data-id="${esc(r.id)}">${esc(r.id)}</button></td><td>${r.type==='cabinet'?'ตู้ดับเพลิง':'ถังดับเพลิง'}</td><td>${esc(r.location)}</td><td>${esc(r.floor)}</td><td>${r.checks.filter(x=>x.status==='bad').map(x=>esc(x.name)).join(', ')}</td><td>${dateText(r.date)}</td><td><button class="action-btn" data-id="${esc(r.id)}">รายละเอียด</button></td></tr>`).join(''):`<tr><td colspan="7" style="text-align:center;color:#8b94a3;padding:30px">ยังไม่มีรายการชำรุด</td></tr>`;$$('[data-id]').forEach(b=>b.onclick=()=>showDetail(b.dataset.id));}
function renderEquipment(){const q=$('#equipmentSearch').value.toLowerCase(),st=$('#statusFilter').value,kind=$('#kindFilter').value;const rs=records.filter(r=>(!q||`${r.id} ${r.location} ${r.floor}`.toLowerCase().includes(q))&&(st==='all'||r.status===st)&&(kind==='all'||r.type===kind));$('#equipmentBody').innerHTML=rs.length?rs.map(r=>`<tr><td><button class="id-link" data-id="${esc(r.id)}">${esc(r.id)}</button></td><td>${r.type==='cabinet'?'ตู้ดับเพลิง':'ถังดับเพลิง'}${r.extType?' ('+esc(r.extType)+')':''}</td><td>${esc(r.location)}</td><td>${esc(r.floor)}</td><td><span class="status ${r.status}">${r.status==='good'?'ปกติ':'ชำรุด'}</span></td><td>${dateText(r.date)}</td><td><button class="action-btn" data-id="${esc(r.id)}">ดู</button> <button class="action-btn delete" data-delete="${esc(r.id)}">ลบ</button></td></tr>`).join(''):`<tr><td colspan="7" style="text-align:center;color:#8b94a3;padding:30px">ไม่พบข้อมูล</td></tr>`;$$('#equipmentBody [data-id]').forEach(b=>b.onclick=()=>showDetail(b.dataset.id));$$('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('ยืนยันการลบรายการ '+b.dataset.delete+' ?')){records=records.filter(r=>r.id!==b.dataset.delete);save();toast('ลบรายการแล้ว')}})}
function showDetail(id){const r=records.find(x=>x.id===id);if(!r)return;$('#modalContent').innerHTML=`<h2>รายละเอียด ${esc(r.id)}</h2><p style="color:#87909f">ผลการตรวจ ${dateText(r.date)} โดย ${esc(r.inspector)}</p><div class="detail-grid"><div class="detail-item"><small>ประเภท</small><b>${r.type==='cabinet'?'ตู้ดับเพลิง':'ถังดับเพลิง'} ${r.extType?'— '+esc(r.extType):''}</b></div><div class="detail-item"><small>สถานที่</small><b>${esc(r.location)} / ${esc(r.floor)}</b></div><div class="detail-item"><small>สถานะรวม</small><b class="${r.status==='bad'?'bad-text':'good-text'}">${r.status==='bad'?'ชำรุด':'ปกติ'}</b></div><div class="detail-item"><small>ขนาด</small><b>${r.size?esc(r.size)+' lbs':'—'}</b></div></div><h3>ผลการตรวจรายหัวข้อ</h3><table><tbody>${r.checks.map(c=>`<tr><td>${esc(c.name)}</td><td><span class="status ${c.status}">${c.status==='good'?'ปกติ':'ชำรุด'}</span></td></tr>`).join('')}</tbody></table>${r.note?`<p><b>หมายเหตุ:</b> ${esc(r.note)}</p>`:''}`;$('#modal').classList.remove('hidden')}
$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
$('#dashboardSearch').oninput=e=>renderDashboard(e.target.value);$('#globalSearch').oninput=e=>{const v=e.target.value;if(v){page('dashboard');$('#dashboardSearch').value=v;renderDashboard(v)}};$('#clearFilter').onclick=()=>{$('#dashboardSearch').value='';renderDashboard()};['#equipmentSearch','#statusFilter','#kindFilter'].forEach(s=>$(s).oninput=renderEquipment);
function renderAll(){locations();renderDashboard($('#dashboardSearch')?.value||'');renderEquipment();$('#lastSynced').textContent=nowText()}
setDate();renderType();renderAll();
