/* Fire Safety Inspection - Supabase production client */
const SUPABASE_URL='https://yrhjklnxjchfxbcpopfd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable__SxBsu9fKpxjS7YPaAyTqA_lqwZW62K';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let currentUser=null,currentProfile=null,pendingPhotos=[];
const rows={cabinet:[['สภาพตู้','เช็คสนิม, กระจกแตก, บานพับ'],['สายฉีด','เช็ครอยรั่ว, การพับงอ'],['ชุดแองเกิลวาล์ว','เช็คสภาพวาล์ว, สนิม'],['ยางโอริงหัวจ่าย','เช็คความยืดหยุ่น, การฉีกขาด'],['วาล์วน้ำ','เช็คการเปิด-ปิด, การรั่วซึม']],extinguisher:[['มาตรวัด','เข็มอยู่ในแถบสีเขียว (ยกเว้น CO2)'],['ซีล/สลัก','ล็อคแน่นหนา ไม่ขาด'],['สายฉีด','ไม่เปื่อย ไม่ตัน'],['สภาพถัง','เช็คสนิม, รอยบุบ, สีถลอก']]};
const typeText={cabinet:'ตู้ดับเพลิง',extinguisher:'ถังดับเพลิง'};
const extMap={'เคมีแห้ง':'dry_chemical','CO2':'co2','Fire Ade':'fire_ade','AVD':'avd'};
const extLabel={dry_chemical:'เคมีแห้ง',co2:'CO2',fire_ade:'Fire Ade',avd:'AVD'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const dateText=d=>d?new Date(d).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):'—';
const nowText=()=>dateText(new Date());
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function page(p){$$('.page').forEach(x=>x.classList.remove('active-page'));$('#'+p)?.classList.add('active-page');$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));scrollTo({top:0,behavior:'smooth'});if(p==='dashboard')loadDashboard($('#dashboardSearch')?.value||'');if(p==='equipment')loadEquipment()}
$$('#nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));
$('#newInspection').onclick=()=>page('inspection');$('#addFromList').onclick=()=>page('inspection');
$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');
$('#scanBtn').onclick=()=>toast('ระบบสแกน QR/Barcode จะเชื่อมต่อกล้องในขั้นถัดไป — ตอนนี้กรอกรหัสอุปกรณ์ได้ทันที');

function checkRows(type,prefix){return rows[type].map((r,i)=>`<div class="check-row" data-check="${prefix}-${i}"><div><strong>${r[0]}</strong><small>${r[1]}</small></div><div class="check-status"><label><input type="radio" name="${prefix}-c${i}" value="good"> ปกติ</label><label><input type="radio" name="${prefix}-c${i}" value="bad"> ชำรุด</label></div>${i===rows[type].length-1?`<input class="check-note" data-note="${prefix}" placeholder="หมายเหตุ / อาการเสีย">`:'<span></span>'}</div>`).join('')}
function renderEquipmentForms(){const selected=$$('input[name="equipmentTypes"]:checked').map(x=>x.value),box=$('#equipmentForms');box.innerHTML=selected.map(type=>type==='cabinet'?`<div class="equipment-block"><div class="block-head"><span>🧯</span><div><h3>ตู้ดับเพลิง</h3><small>Fire Hose Cabinet</small></div></div><div class="checklist">${checkRows('cabinet','cabinet')}</div></div>`:`<div class="equipment-block"><div class="block-head"><span>🧯</span><div><h3>ถังดับเพลิง</h3><small>Fire Extinguisher</small></div></div><div class="fields"><label>ประเภทถัง<select class="ext-type"><option>เคมีแห้ง</option><option>CO2</option><option>Fire Ade</option><option>AVD</option></select></label><label>ขนาดปอนด์<input class="ext-size" type="number" min="1" placeholder="เช่น 10, 15, 20"></label></div><div class="checklist">${checkRows('extinguisher','extinguisher')}</div></div>`).join('');const ext=$('.ext-type');if(ext){ext.onchange=toggleGauge;toggleGauge()}}
$$('input[name="equipmentTypes"]').forEach(x=>x.onchange=renderEquipmentForms);
function toggleGauge(){const t=$('.ext-type'),row=$('[data-check="extinguisher-0"]');if(!t||!row)return;const hide=t.value==='CO2';row.classList.toggle('hidden',hide);row.querySelectorAll('input').forEach(x=>{x.disabled=hide;x.required=false})}
function setDate(){$('#inspectionDate').value=nowText();if(currentProfile)$('#inspectorName').value=currentProfile.full_name}
function resetInspection(){pendingPhotos=[];renderPhotos();$('#inspectionForm').reset();setTimeout(()=>{$$('[name="equipmentTypes"]').forEach(x=>x.checked=false);renderEquipmentForms();setDate()},0)}
$('#inspectionForm').addEventListener('reset',()=>setTimeout(()=>{pendingPhotos=[];renderPhotos();setDate();$$('[name="equipmentTypes"]').forEach(x=>x.checked=false);renderEquipmentForms()},0));

function resizePhoto(file){return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=e=>{const im=new Image();im.onload=()=>{const max=1600,s=Math.min(1,max/im.width,max/im.height),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>resolve(b),'image/jpeg',.78)};im.onerror=reject;im.src=e.target.result};rd.onerror=reject;rd.readAsDataURL(file)})}
$('#photoInput').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;toast('กำลังเตรียมรูปภาพ...');for(const f of files){if(f.type.startsWith('image/'))try{pendingPhotos.push({blob:await resizePhoto(f),name:f.name})}catch(err){console.error(err)}}e.target.value='';renderPhotos();toast(`เพิ่มรูปภาพแล้ว ${pendingPhotos.length} รูป`)};
function renderPhotos(){$('#photoPreview').innerHTML=pendingPhotos.map((p,i)=>{const url=URL.createObjectURL(p.blob);return `<div class="photo-item"><img src="${url}" alt="รูปตรวจ ${i+1}"><button type="button" data-photo="${i}">×</button><div class="photo-caption">รูปที่ ${i+1}</div></div>`}).join('');$$('[data-photo]').forEach(b=>b.onclick=()=>{pendingPhotos.splice(+b.dataset.photo,1);renderPhotos()})}
function collectComponent(type){const prefix=type==='cabinet'?'cabinet':'extinguisher',checks=[];$$(`[data-check^="${prefix}-"]`).forEach(r=>{if(r.classList.contains('hidden'))return;checks.push({name:r.querySelector('strong').textContent,status:r.querySelector('input:checked')?.value||null})});return{type,extType:type==='extinguisher'?$('.ext-type')?.value:'',size:type==='extinguisher'?$('.ext-size')?.value:'',checks,note:$(`[data-note="${prefix}"]`)?.value||'',status:checks.some(x=>x.status==='bad')?'bad':'good'}}

async function getLocation(name,floor){let {data,error}=await db.from('locations').select('*').ilike('location_name',name).eq('floor',floor).limit(1).maybeSingle();if(error)throw error;if(!data)throw new Error('ไม่พบจุดติดตั้งนี้ในฐานข้อมูล กรุณาเลือกจุดที่มีอยู่');return data}
async function getOrCreateEquipment(code,locationId,component){let {data,error}=await db.from('equipment').select('*').eq('equipment_code',code).maybeSingle();if(error)throw error;if(data)return data;const payload={equipment_code:code,location_id:locationId,equipment_type:component.type,extinguisher_type:component.type==='extinguisher'?extMap[component.extType]:null,size_lbs:component.type==='extinguisher'?Number(component.size):null};let r=await db.from('equipment').insert(payload).select().single();if(r.error)throw r.error;return r.data}
async function uploadPhotos(inspectionId){const uploaded=[];for(const p of pendingPhotos){const path=`${currentUser.id}/${inspectionId}/${crypto.randomUUID()}.jpg`;const up=await db.storage.from('inspection-photos').upload(path,p.blob,{contentType:'image/jpeg',upsert:false});if(up.error)throw up.error;const ins=await db.from('inspection_photos').insert({inspection_id:inspectionId,storage_path:path,file_name:p.name,uploaded_by:currentUser.id}).select().single();if(ins.error)throw ins.error;uploaded.push(ins.data)}return uploaded}

$('#inspectionForm').onsubmit=async e=>{e.preventDefault();if(!currentUser)return;const types=$$('input[name="equipmentTypes"]:checked').map(x=>x.value);if(!types.length){toast('กรุณาเลือกอุปกรณ์อย่างน้อย 1 ประเภท');return}for(const type of types){for(let i=0;i<rows[type].length;i++){if(type==='extinguisher'&&i===0&&$('.ext-type')?.value==='CO2')continue;if(!document.querySelector(`input[name="${type}-c${i}"]:checked`)){toast(`กรุณาระบุผลตรวจ: ${rows[type][i][0]}`);return}}}const locationName=$('#location').value.trim(),floor=$('#floor').value,baseCode=$('#equipmentId').value.trim();if(!locationName||!floor||!baseCode){toast('กรุณากรอกข้อมูลพื้นฐานให้ครบ');return}const btn=e.submitter;btn.disabled=true;btn.textContent='⏳ กำลังบันทึก...';try{const loc=await getLocation(locationName,floor);const components=types.map(collectComponent);for(const c of components){if(c.type==='extinguisher'&&(!c.extType||!c.size)){throw new Error('กรุณาระบุประเภทและขนาดถังดับเพลิง')}const code=types.length>1?`${baseCode}-${c.type==='cabinet'?'C':'E'}`:baseCode;const eq=await getOrCreateEquipment(code,loc.id,c);const ins=await db.from('inspections').insert({equipment_id:eq.id,inspector_id:currentUser.id,inspected_at:new Date().toISOString(),overall_status:c.status,general_note:c.note||null}).select().single();if(ins.error)throw ins.error;for(const item of c.checks){const ii=await db.from('inspection_items').insert({inspection_id:ins.data.id,item_code:item.name,item_name:item.name,status:item.status,note:item.name===c.checks[c.checks.length-1].name?c.note:null});if(ii.error)throw ii.error}if(pendingPhotos.length)await uploadPhotos(ins.data.id)}await db.from('audit_logs').insert({user_id:currentUser.id,action:'create_inspection',table_name:'inspections',details:{location:locationName,floor,equipment_types:types}});toast(`บันทึกสำเร็จ ${types.length} รายการ • รูป ${pendingPhotos.length} รูป`);resetInspection();await loadDashboard();await loadEquipment();page('equipment')}catch(err){console.error(err);toast(err.message||'บันทึกข้อมูลไม่สำเร็จ')}finally{btn.disabled=false;btn.textContent='💾 บันทึกข้อมูล'}};

async function loadLocations(){const {data,error}=await db.from('locations').select('location_name,floor').eq('is_active',true).order('location_name');if(error){console.error(error);return}const unique=[...new Map(data.map(x=>[`${x.location_name}|${x.floor}`,x])).values()];$('#locationOptions').innerHTML=unique.map(x=>`<option value="${esc(x.location_name)}">${esc(x.floor)}</option>`).join('')}
async function loadDashboard(filter=''){const {data,error}=await db.from('latest_equipment_status').select('*');if(error){console.error(error);toast('โหลด Dashboard ไม่สำเร็จ');return}let rs=data||[];if(filter)rs=rs.filter(r=>(r.location_name||'').toLowerCase().includes(filter.toLowerCase())||(r.equipment_code||'').toLowerCase().includes(filter.toLowerCase()));const total=rs.length,good=rs.filter(r=>r.overall_status==='good').length,bad=rs.filter(r=>r.overall_status==='bad').length;$('#mLocations').textContent=new Set(rs.map(r=>r.location_id)).size;$('#mTotal').textContent=total;$('#mGood').textContent=good;$('#mBad').textContent=bad;$('#mGoodPct').textContent=total?Math.round(good/total*100)+'%':'0%';$('#legGood').textContent=good;$('#legBad').textContent=bad;const pct=total?good/total:0;$('#donut').style.background=`conic-gradient(#16854d 0 ${pct*360}deg,#dc3342 ${pct*360}deg 360deg)`;$('#donutPct').textContent=Math.round(pct*100)+'%';const floors=[...new Set((data||[]).map(r=>r.floor))];const max=Math.max(1,...floors.map(f=>rs.filter(r=>r.floor===f&&r.overall_status==='bad').length));$('#floorChart').innerHTML=(floors.length?floors:['ชั้น 1']).map(f=>{const n=rs.filter(r=>r.floor===f&&r.overall_status==='bad').length;return `<div class="bar-item"><b>${n}</b><div class="bar" style="height:${Math.max(3,n/max*145)}px"></div><small>${esc(f)}</small></div>`}).join('');const counts=['dry_chemical','co2','fire_ade','avd'].map(t=>rs.filter(r=>r.extinguisher_type===t).length),sum=counts.reduce((a,b)=>a+b,0);let acc=0;const cols=['#d93b45','#58677a','#d58a2c','#3b8f65'];const stops=counts.map((n,i)=>{const s=sum?acc/sum*360:0;acc+=n;return `${cols[i]} ${s}deg ${sum?acc/sum*360:0}deg`}).join(',');$('#pie').style.background=sum?`conic-gradient(${stops})`:'#e8edf3';$('#typeLegend').innerHTML=['dry_chemical','co2','fire_ade','avd'].map((t,i)=>`<span><i class="dot" style="background:${cols[i]}"></i>${extLabel[t]} <b>${counts[i]}</b></span>`).join('');const badRs=rs.filter(r=>r.overall_status==='bad').sort((a,b)=>String(b.inspected_at).localeCompare(String(a.inspected_at)));$('#alertsBody').innerHTML=badRs.length?badRs.map(r=>`<tr><td><button class="id-link" data-eqid="${esc(r.equipment_id)}">${esc(r.equipment_code)}</button></td><td>${typeText[r.equipment_type]}</td><td>${esc(r.location_name)}</td><td>${esc(r.floor)}</td><td>ดูรายละเอียด</td><td>${dateText(r.inspected_at)}</td><td><button class="action-btn" data-eqid="${esc(r.equipment_id)}">รายละเอียด</button></td></tr>`).join(''):`<tr><td colspan="7" style="text-align:center;color:#8b94a3;padding:30px">ยังไม่มีรายการชำรุด</td></tr>`;$$('[data-eqid]').forEach(b=>b.onclick=()=>showDetail(b.dataset.eqid));$('#lastSynced').textContent=nowText()}

async function loadEquipment(){const {data,error}=await db.from('latest_equipment_status').select('*').order('equipment_code');if(error){console.error(error);toast('โหลดรายการอุปกรณ์ไม่สำเร็จ');return}const q=($('#equipmentSearch').value||'').toLowerCase(),st=$('#statusFilter').value,kind=$('#kindFilter').value,rs=(data||[]).filter(r=>(!q||`${r.equipment_code} ${r.location_name} ${r.floor}`.toLowerCase().includes(q))&&(st==='all'||r.overall_status===st)&&(kind==='all'||r.equipment_type===kind));$('#equipmentBody').innerHTML=rs.length?rs.map(r=>`<tr><td><button class="id-link" data-eqid="${esc(r.equipment_id)}">${esc(r.equipment_code)}</button></td><td>🧯 ${typeText[r.equipment_type]}${r.extinguisher_type?' ('+esc(extLabel[r.extinguisher_type])+' '+esc(r.size_lbs)+' lbs)':''}</td><td>${esc(r.location_name)}</td><td>${esc(r.floor)}</td><td><span class="status ${r.overall_status||''}">${r.overall_status==='good'?'ปกติ':r.overall_status==='bad'?'ชำรุด':'ยังไม่ตรวจ'}</span></td><td>${dateText(r.inspected_at)}</td><td><button class="action-btn" data-eqid="${esc(r.equipment_id)}">ดู</button></td></tr>`).join(''):`<tr><td colspan="7" style="text-align:center;color:#8b94a3;padding:30px">ไม่พบข้อมูล</td></tr>`;$$('#equipmentBody [data-eqid]').forEach(b=>b.onclick=()=>showDetail(b.dataset.eqid))}
['#equipmentSearch','#statusFilter','#kindFilter'].forEach(s=>$(s).addEventListener('input',()=>loadEquipment()));
$('#dashboardSearch').addEventListener('input',e=>loadDashboard(e.target.value));$('#globalSearch').addEventListener('input',e=>{if(e.target.value){$('#dashboardSearch').value=e.target.value;page('dashboard')}});$('#clearFilter').onclick=()=>{$('#dashboardSearch').value='';loadDashboard()};

async function showDetail(equipmentId){const {data:eq,error:eqErr}=await db.from('equipment').select('*,locations(location_name,floor)').eq('id',equipmentId).single();if(eqErr){toast('ไม่สามารถโหลดรายละเอียดได้');return}const {data:ins,error:insErr}=await db.from('inspections').select('*,profiles(full_name),inspection_items(*),inspection_photos(*)').eq('equipment_id',equipmentId).order('inspected_at',{ascending:false}).limit(1).maybeSingle();if(insErr){toast('ไม่สามารถโหลดประวัติได้');return}let photos='';if(ins?.inspection_photos?.length){const urls=await Promise.all(ins.inspection_photos.map(async p=>{const r=await db.storage.from('inspection-photos').createSignedUrl(p.storage_path,3600);return r.data?.signedUrl}));photos=urls.filter(Boolean).map(u=>`<img src="${u}" style="width:100px;height:80px;object-fit:cover;border-radius:8px;margin:4px">`).join('')}$('#modalContent').innerHTML=`<h2>${esc(eq.equipment_code)} — ${typeText[eq.equipment_type]}</h2><p style="color:#87909f">${esc(eq.locations?.location_name||'')} • ${esc(eq.locations?.floor||'')}</p><div class="detail-grid"><div class="detail-item"><small>สถานะล่าสุด</small><b>${ins?.overall_status==='bad'?'ชำรุด':ins?.overall_status==='good'?'ปกติ':'ยังไม่ตรวจ'}</b></div><div class="detail-item"><small>ตรวจล่าสุด</small><b>${dateText(ins?.inspected_at)}</b></div><div class="detail-item"><small>ผู้ตรวจ</small><b>${esc(ins?.profiles?.full_name||'—')}</b></div><div class="detail-item"><small>ประเภทถัง</small><b>${eq.extinguisher_type?extLabel[eq.extinguisher_type]+' '+esc(eq.size_lbs)+' lbs':'—'}</b></div></div>${ins?`<h3>ผลการตรวจ</h3><table><tbody>${(ins.inspection_items||[]).map(c=>`<tr><td>${esc(c.item_name)}</td><td><span class="status ${c.status}">${c.status==='good'?'ปกติ':'ชำรุด'}</span></td></tr>`).join('')}</tbody></table>${ins.general_note?`<p><b>หมายเหตุ:</b> ${esc(ins.general_note)}</p>`:''}<h3>📷 รูปภาพการตรวจ</h3><div>${photos||'ไม่มีรูปภาพ'}</div>`:'<p>ยังไม่มีประวัติการตรวจ</p>'}`;$('#modal').classList.remove('hidden')}

async function startApp(session){currentUser=session.user;let p=await db.from('profiles').select('*').eq('id',currentUser.id).single();if(p.error){console.error(p.error);$('#authMsg').textContent='ไม่พบข้อมูลผู้ใช้งาน';return}currentProfile=p.data;$('#userName').textContent=currentProfile.full_name;$('#userRoleLabel').textContent=currentProfile.role==='admin'?'ผู้ดูแลระบบ':currentProfile.role==='supervisor'?'หัวหน้างาน':'ผู้ตรวจ';$('#inspectorName').value=currentProfile.full_name;$('#authScreen').classList.add('app-hidden');$('#appShell').classList.remove('app-hidden');setDate();await loadLocations();await loadDashboard();await loadEquipment()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#authMsg').textContent='กำลังเข้าสู่ระบบ...';const {data,error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){$('#authMsg').textContent=error.message.includes('Invalid login')?'อีเมลหรือรหัสผ่านไม่ถูกต้อง':error.message;return}$('#authMsg').textContent=''};
$('#logout').onclick=async()=>{await db.auth.signOut();currentUser=null;currentProfile=null;$('#appShell').classList.add('app-hidden');$('#authScreen').classList.remove('app-hidden');$('#loginPassword').value='';toast('ออกจากระบบแล้ว')};
db.auth.onAuthStateChange(async(_event,session)=>{if(session)await startApp(session);else{$('#appShell').classList.add('app-hidden');$('#authScreen').classList.remove('app-hidden')}});
(async()=>{const {data}=await db.auth.getSession();if(data.session)await startApp(data.session);else{$('#appShell').classList.add('app-hidden');$('#authScreen').classList.remove('app-hidden')}})();
