const SUPABASE_URL='https://yrhjklnxjchfxbcpopfd.supabase.co';
const SUPABASE_KEY='sb_publishable__SxBsu9fKpxjS7YPaAyTqA_lqwZW62K';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const token=(new URLSearchParams(location.search).get('qr')||'').trim();let user,profile,loc,equipment=[],photoFiles=[];
const ext={dry_chemical:'เคมีแห้ง',co2:'CO2',fire_ade:'Fire Ade',avd:'AVD',bf2000:'BF2000'};const checks={cabinet:['สภาพตู้','สายฉีด','ชุดแองเกิลวาล์ว','ยางโอริงหัวจ่าย','วาล์วน้ำ'],extinguisher:['มาตรวัด','ซีล/สลัก','สายฉีด','สภาพถัง']};
function show(id){['scanState','loginState','app','done'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}function toast(t){const x=$('#toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',3000)}
async function boot(){if(!token){show('scanState');return}const {data:{session}}=await db.auth.getSession();if(!session){show('loginState');return}await enter(session.user)}
async function enter(u){user=u;let r=await db.from('profiles').select('full_name,role,is_active').eq('id',u.id).single();if(r.error||!r.data?.is_active||!['fireman','inspector','supervisor','admin'].includes(r.data.role)){await db.auth.signOut();show('loginState');$('#loginMsg').textContent='บัญชีนี้ไม่มีสิทธิ์ใช้งาน';return}profile=r.data;$('#logout').classList.remove('hidden');r=await db.rpc('resolve_fireman_qr',{p_token:token});if(r.error||!r.data?.length){show('scanState');$('#scanState h1').textContent='QR ไม่ถูกต้องหรือไม่ได้ใช้งาน';return}loc=r.data[0];r=await db.from('equipment').select('*').eq('location_id',loc.location_id).eq('is_active',true).order('equipment_type').order('equipment_code');if(r.error)throw r.error;equipment=r.data||[];render();show('app')}
function render(){$('#locCode').textContent=loc.location_code;$('#locName').textContent=loc.location_name;$('#floor').textContent=loc.floor||'-';$('#building').textContent=loc.building?' • '+loc.building:'';$('#when').textContent='วันที่ตรวจ: '+new Date().toLocaleString('th-TH');const codes=[...Array.from({length:6},(_,i)=>`M${i+1}`),...Array.from({length:10},(_,i)=>`S${i+1}`)];$('#inspector').innerHTML='<option value="">เลือกชื่อผู้ตรวจ</option>'+codes.map(x=>`<option>${x}</option>`).join('');let h='';equipment.forEach((e,i)=>{let names=checks[e.equipment_type]||[];if(e.equipment_type==='extinguisher'&&e.extinguisher_type==='co2')names=names.filter(x=>x!=='มาตรวัด');const isExt=e.equipment_type==='extinguisher';h+=`<section class="card eq" data-index="${i}"><div class="equipment-head"><div><h2>${esc(e.equipment_code)}</h2><small>${esc(e.equipment_label||'')}</small></div><span class="type">${isExt?'ถังดับเพลิง':'ตู้ดับเพลิง'}</span></div><div class="meta">${isExt?`ประเภท: <b>${esc(ext[e.extinguisher_type]||e.extinguisher_type||'-')}</b> • ขนาด: <b>${esc(e.size_lbs||'-')} lbs</b>`:`Fire Hose Cabinet${e.extinguisher_type?' • ภายในมี '+esc(ext[e.extinguisher_type]||e.extinguisher_type):''}`}</div>${names.map((x,j)=>`<div class="check"><div class="check-title">${esc(x)}</div><div class="choices"><label class="choice good"><input required type="radio" name="c-${i}-${j}" value="good"><span>✓ ปกติ</span></label><label class="choice bad"><input required type="radio" name="c-${i}-${j}" value="bad"><span>✕ ชำรุด</span></label></div></div>`).join('')}<label class="note">หมายเหตุ<textarea rows="2" data-note></textarea></label></section>`});$('#equipment').innerHTML=h||'<section class="card state"><h2>จุดนี้ยังไม่มีอุปกรณ์</h2></section>'}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='กำลังเข้าสู่ระบบ...';const r=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(r.error){$('#loginMsg').textContent='เข้าสู่ระบบไม่สำเร็จ';return}await enter(r.data.user)};$('#logout').onclick=async()=>{await db.auth.signOut();location.href='fireman.html'};
$('#photos').onchange=e=>{photoFiles=[...e.target.files];$('#preview').innerHTML='';photoFiles.forEach(f=>{const im=document.createElement('img');im.src=URL.createObjectURL(f);$('#preview').appendChild(im)})};
async function compressPhoto(file){if(!file?.type?.startsWith('image/'))return file;const bitmap=await createImageBitmap(file);const maxSide=960;let w=bitmap.width,h=bitmap.height;if(Math.max(w,h)>maxSide){const scale=maxSide/Math.max(w,h);w=Math.round(w*scale);h=Math.round(h*scale)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.drawImage(bitmap,0,0,w,h);bitmap.close?.();const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('ไม่สามารถย่อรูปได้')),'image/jpeg',0.45));return new File([blob],(file.name||'photo').replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg',lastModified:Date.now()})}
async function upload(id){for(const original of photoFiles){const f=await compressPhoto(original);const safe=(f.name||'photo.jpg').replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${user.id}/${id}/${Date.now()}-${Math.random().toString(36).slice(2)}-${safe}`;let r=await db.storage.from('inspection-photos').upload(path,f,{contentType:'image/jpeg'});if(r.error)throw r.error;r=await db.from('inspection_photos').insert({inspection_id:id,storage_path:path,file_name:f.name||safe,uploaded_by:user.id});if(r.error)throw r.error}}
$('#form').onsubmit=async e=>{e.preventDefault();if(!$('#inspector').value){toast('กรุณาเลือกชื่อผู้ตรวจ');return}if(!equipment.length){toast('จุดนี้ไม่มีอุปกรณ์');return}const btn=$('#save');btn.disabled=true;btn.textContent='กำลังย่อรูปและบันทึก...';try{for(let i=0;i<equipment.length;i++){const eq=equipment[i],sec=document.querySelector(`.eq[data-index="${i}"]`);let names=checks[eq.equipment_type]||[];if(eq.equipment_type==='extinguisher'&&eq.extinguisher_type==='co2')names=names.filter(x=>x!=='มาตรวัด');const selected=names.map((_,j)=>sec.querySelector(`input[name="c-${i}-${j}"]:checked`));const status=selected.some(x=>x?.value==='bad')?'bad':'good';const ir=await db.from('inspections').insert({equipment_id:eq.id,inspector_id:user.id,inspector_display_name:$('#inspector').value,inspected_at:new Date().toISOString(),overall_status:status,general_note:sec.querySelector('[data-note]').value.trim()||null}).select('id').single();if(ir.error)throw ir.error;const inspectionId=ir.data.id;for(let j=0;j<names.length;j++){const item=await db.rpc('add_inspection_item',{p_inspection_id:inspectionId,p_item_code:`${eq.equipment_type}-${j+1}`,p_item_name:names[j],p_status:selected[j]?.value||'good',p_note:null});if(item.error)throw item.error}await upload(inspectionId)}show('done')}catch(err){console.error(err);toast('บันทึกไม่สำเร็จ: '+(err.message||'เกิดข้อผิดพลาด'));btn.disabled=false;btn.textContent='💾 บันทึกผลการตรวจ'}};
boot().catch(e=>{console.error(e);show('scanState');$('#scanState h1').textContent='ระบบขัดข้อง กรุณาลองใหม่'});